[functional] add map_field and map_call examples
1bardesign/batteries-examples pull request #1
Opened 2023-03-07 21:40 UTC by TurtleP

2023-03-08 23:10 UTC, 1bardesign requested changes
Just some feedback, would love a few adjustments before we go ahead and merge :pray:

2023-03-08 23:10 UTC, 1bardesign commented on functional.lua
> +function a:position()
so the intent here is less to like, have methods that return a literal, and more that it can be used on class-like objects to do a call (eg to fetch a component by name from a `ferris.entity`)

I think this example kinda confuses things by having the `position` method inline rather than using a class (maybe one of the existing batteries classes)?

eg `functional.map_call({vec2(1, 0), vec2(0, 1)}, "rotate", math.pi)` would get a copy of those vectors, rotated a half turn

2023-03-08 23:10 UTC, 1bardesign commented on functional.lua
> +print_var("sequence_b", functional.map_call({ a, b }, c, 1, 2))
the function example is kinda fine, at least showing that you can provide a function is a good idea.

the main motivator for these is that it avoids having to define functions inline, thereby avoiding generating any garbage if the function you need already exists on the object or somewhere else in your project.

2023-03-08 23:10 UTC, 1bardesign commented on functional.lua
> +local numbers = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }
i dont love these presumably autoformat/linter added whitespace changes for unrelated code

2023-03-08 23:10 UTC, 1bardesign commented on functional.lua
> +local seq_pairs = { { 1, 2 }, { 3, 4 }, { 5, 6 }, { 7, 8 } }
as above, there's no reason to adjust this code afaict

2023-03-08 23:10 UTC, 1bardesign commented on functional.lua
> +local a = { ["a"] = 1,["b"] = 4 }
not sure why this isn't {a = 1, b = 4}; is there a reason to explicitly index by keys like that?

2023-03-08 23:20 UTC, TurtleP commented on functional.lua
> +print_var("sequence_b", functional.map_call({ a, b }, c, 1, 2))
I will probably want to rename the function itself, `c` is kinda, well, bleh.

2023-03-08 23:21 UTC, TurtleP commented on functional.lua
> +local a = { ["a"] = 1,["b"] = 4 }
My brain didn't recall how lua tables work, so I'll do that.

2023-03-09 00:31 UTC, 1bardesign approved these changes

2023-03-09 00:31 UTC, merged

2023-03-09 00:31 UTC, 1bardesign commented
:+1: